import 'bootstrap-icons/font/bootstrap-icons.css';
import '../main.css';
import '../room.css';
import cdmLogo from "../../public/cdm-logo.webp";
import Image from 'next/image';


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header id="nav">
          <div className="nav--list">
            <button id="members__button"></button>
            <a href="lobby.html">
              <h3 id="logo">
                <Image src={cdmLogo} width={45} />
                <span>E-CDM</span>
              </h3>
            </a>
          </div>


          {/* <div id="nav__links">
            <button id="chat__button"></button>

            <a className="nav__link" id="create__room__btn" href="lobby.html">
              Leave
            </a>
          </div> */}
        </header>
        {children}
      </body >
    </html >
  )
}
